from . import res_partner
from . import badminton_session
from . import badminton_sale
from . import badminton_group
from . import badminton_lesson_freeze
from . import badminton_lesson_freeze_wizard
from . import badminton_lesson_simple
from . import customer_wizards
from . import qr_scanner
from . import sport_system
from . import session_extend_wizard
from . import badminton_attendance_check
from . import cash
from . import badminton_session_filter